"""PostgreSQL contracts for the immutable knowledge-claim repository.

Each test relies on this directory's disposable database fixture rather than
cleaning rows itself: the append-only triggers deliberately make teardown by
DELETE impossible.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from uuid import UUID, uuid4

import pytest
import sqlalchemy as sa
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession

from brain_v42.db.tables import brain_entities, knowledge_fact_definitions, project_contexts
from brain_v42.repositories.pg_knowledge_claims import (
    active_claims,
    insert_claim,
    latest_retired,
    retire_claims,
)

pytestmark = pytest.mark.integration

_DIGEST = "a" * 64
_CLAIM_KEY = "b" * 64


async def _scene(session: AsyncSession) -> tuple[UUID, str, str]:
    """Create the valid anchor and definition every repository write requires."""
    project_key = f"claim-repository-{uuid4().hex[:16]}"
    fact_name = f"claim_repository_fact_{uuid4().hex}"
    await session.execute(
        sa.insert(project_contexts).values(
            project_key=project_key,
            name=project_key,
            description="knowledge claim repository integration fixture",
        )
    )
    entity_id = (
        await session.execute(
            sa.insert(brain_entities)
            .values(
                entity_type="learning",
                entity_key=f"claim-repository-entity-{uuid4()}",
                project_key=project_key,
                scope_kind="project",
                lifecycle="active",
            )
            .returning(brain_entities.c.id)
        )
    ).scalar_one()
    await session.execute(
        sa.insert(knowledge_fact_definitions).values(
            fact_name=fact_name,
            definition_version=1,
            target="production",
            ttl_seconds=60,
            timeout_seconds=10,
            policies={},
            value_schema={},
            digest=_DIGEST,
        )
    )
    assert isinstance(entity_id, UUID)
    return entity_id, project_key, fact_name


async def _insert(
    session: AsyncSession,
    *,
    entity_id: UUID,
    project_key: str,
    fact_name: str,
    claim_key: str = _CLAIM_KEY,
    replaces_id: UUID | None = None,
):
    """Write one valid occurrence while each test owns its differing assertion."""
    return await insert_claim(
        session,
        entity_ref_id=entity_id,
        entity_type="learning",
        project_key=project_key,
        claim_key=claim_key,
        statement="The PostgreSQL claim repository preserves this assertion.",
        fact_name=fact_name,
        definition_version=1,
        target="production",
        expected={"path": "/lag_seconds", "op": "lte", "value": 300},
        expected_resolved={"path": "/lag_seconds", "op": "lte", "value": 300},
        validity_seconds=60,
        provenance="declared",
        declared_by="integration-test",
        declared_at=datetime.now(UTC),
        replaces_id=replaces_id,
    )


async def test_insert_claim_returns_server_generated_row(engine: AsyncEngine) -> None:
    """Removing RETURNING would lose identity and JSON objects generated by PostgreSQL."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        row = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )

        assert isinstance(row.id, UUID)
        assert row.seq > 0
        assert isinstance(row.recorded_at, datetime)
        assert row.expected == {"path": "/lag_seconds", "op": "lte", "value": 300}
        assert row.expected_resolved == {"path": "/lag_seconds", "op": "lte", "value": 300}


async def test_insert_claim_assigns_strictly_increasing_sequence(engine: AsyncEngine) -> None:
    """Dropping the server identity order would make adjacent rows unordered."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        first = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        second = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            claim_key="c" * 64,
        )

        assert first.seq < second.seq


async def test_active_claims_returns_only_active_rows_in_sequence_order(
    engine: AsyncEngine,
) -> None:
    """Removing the retirement filter or ORDER BY would expose a wrong CAS set."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        first = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        second = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            claim_key="c" * 64,
        )
        third = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            claim_key="d" * 64,
        )
        assert await retire_claims(session, [first.id], retired_at=datetime.now(UTC)) == 1

        active = await active_claims(session, entity_id)

        assert [row.id for row in active] == [second.id, third.id]
        assert await active_claims(session, uuid4()) == []


async def test_retire_claims_retires_named_active_rows_and_empty_is_statement_free(
    engine: AsyncEngine,
) -> None:
    """Removing the empty guard would turn a no-op replacement into needless SQL."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        first = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        second = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            claim_key="c" * 64,
        )
        statements: list[str] = []

        def record_statement(
            connection: object,
            cursor: object,
            statement: str,
            parameters: object,
            context: object,
            executemany: bool,
        ) -> None:
            statements.append(statement)

        sa.event.listen(engine.sync_engine, "before_cursor_execute", record_statement)
        try:
            assert await retire_claims(session, [], retired_at=datetime.now(UTC)) == 0
        finally:
            sa.event.remove(engine.sync_engine, "before_cursor_execute", record_statement)
        assert statements == []

        retired_at = datetime.now(UTC) + timedelta(seconds=1)
        assert await retire_claims(session, [first.id], retired_at=retired_at) == 1
        active = await active_claims(session, entity_id)
        assert [row.id for row in active] == [second.id]


async def test_retire_claims_skips_an_already_retired_row(engine: AsyncEngine) -> None:
    """Removing retired_at IS NULL would invoke the trigger on a second retirement."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        row = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        retired_at = datetime.now(UTC)
        assert await retire_claims(session, [row.id], retired_at=retired_at) == 1

        assert await retire_claims(session, [row.id], retired_at=retired_at) == 0


async def test_latest_retired_returns_only_greatest_retired_sequence(engine: AsyncEngine) -> None:
    """Ordering by anything but seq would choose an invalid replacement predecessor."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        first = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        assert await retire_claims(session, [first.id], retired_at=datetime.now(UTC)) == 1
        second = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            replaces_id=first.id,
        )
        assert await retire_claims(session, [second.id], retired_at=datetime.now(UTC)) == 1
        active = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            claim_key="c" * 64,
        )

        assert await latest_retired(session, entity_id, _CLAIM_KEY) == second.id
        assert await latest_retired(session, entity_id, active.claim_key) is None
        assert await latest_retired(session, entity_id, "d" * 64) is None


async def test_insert_claim_requires_the_latest_retired_predecessor(engine: AsyncEngine) -> None:
    """The chain trigger must reject a replacement that skips a retired occurrence."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, project_key, fact_name = await _scene(session)
        first = await _insert(
            session, entity_id=entity_id, project_key=project_key, fact_name=fact_name
        )
        assert await retire_claims(session, [first.id], retired_at=datetime.now(UTC)) == 1
        second = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            replaces_id=await latest_retired(session, entity_id, _CLAIM_KEY),
        )
        assert await retire_claims(session, [second.id], retired_at=datetime.now(UTC)) == 1

        latest = await latest_retired(session, entity_id, _CLAIM_KEY)
        assert latest == second.id
        replacement = await _insert(
            session,
            entity_id=entity_id,
            project_key=project_key,
            fact_name=fact_name,
            replaces_id=latest,
        )
        assert replacement.replaces_id == second.id
        assert await retire_claims(session, [replacement.id], retired_at=datetime.now(UTC)) == 1

        with pytest.raises(DBAPIError, match="latest retired occurrence"):
            async with session.begin_nested():
                await _insert(
                    session,
                    entity_id=entity_id,
                    project_key=project_key,
                    fact_name=fact_name,
                    replaces_id=first.id,
                )


async def test_insert_claim_surfaces_anchor_project_key_refusal(engine: AsyncEngine) -> None:
    """The repository must preserve the anchor trigger's diagnostic unwrapped."""
    async with AsyncSession(engine) as session, session.begin():
        entity_id, _project_key, fact_name = await _scene(session)

        with pytest.raises(DBAPIError, match="anchor project_key mismatch"):
            async with session.begin_nested():
                await _insert(
                    session,
                    entity_id=entity_id,
                    project_key=f"other-{uuid4().hex[:12]}",
                    fact_name=fact_name,
                )
